name: Update Docker Hub Description

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - '.github/workflows/dockerhub-description.yml'
  workflow_dispatch:

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: stgmt/mcp-server-tester-sse-http-stdio
          readme-filepath: ./README.md
          short-description: "🧪 MCP Server Testing Framework - Universal testing tool for Model Context Protocol servers with SSE, HTTP, and STDIO support"
          enable-url-completion: true